// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSight.Infrastructure.Persistence;

#nullable disable

namespace OpenSight.Infrastructure.Migrations
{
    [DbContext(typeof(OpenSightDbContext))]
    partial class OpenSightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenSight.Domain.Entities.Alert", b =>
                {
                    b.Property<string>("AlertId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("bit");

                    b.Property<double?>("AnomalyScore")
                        .HasColumnType("float");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedEndpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RequestRatePct")
                        .HasColumnType("float");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Silenced")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("ZScore")
                        .HasColumnType("float");

                    b.HasKey("AlertId");

                    b.HasIndex("ClientId", "CreatedAt");

                    b.ToTable("Alert", (string)null);
                });

            modelBuilder.Entity("OpenSight.Domain.Entities.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("OpenSight.Domain.Entities.CorrelationEvent", b =>
                {
                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BehavioralAlertId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformanceAlertId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CorrelationId");

                    b.HasIndex("BehavioralAlertId");

                    b.HasIndex("PerformanceAlertId");

                    b.ToTable("CorrelationEvent", (string)null);
                });

            modelBuilder.Entity("OpenSight.Domain.Entities.Alert", b =>
                {
                    b.HasOne("OpenSight.Domain.Entities.Client", "Client")
                        .WithMany("Alerts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OpenSight.Domain.Entities.CorrelationEvent", b =>
                {
                    b.HasOne("OpenSight.Domain.Entities.Alert", "BehavioralAlert")
                        .WithMany()
                        .HasForeignKey("BehavioralAlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenSight.Domain.Entities.Alert", "PerformanceAlert")
                        .WithMany()
                        .HasForeignKey("PerformanceAlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BehavioralAlert");

                    b.Navigation("PerformanceAlert");
                });

            modelBuilder.Entity("OpenSight.Domain.Entities.Client", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}